EL WORKER ES NECESARIO PARA QUE CARGUE EL MODELO EN MEMORIA Y NO EN EL THREAD PRINCIPAL

CREAR UN HOOK ESPECIFICAMENTE PARA MODELOS LOCALES

Y CRAR OTRO PARA EL USO DE APIS EXTERNALES

EL SELECTOR DE MODELOS ESTARÁ EN EL TASKBAR ESTILO WINDOWS 95

SERA UN SELECTOR DOBLE:
	LOCAL> MODELOS
	API> MODELOS